### ISSUE TITLE
Skipping X messages

### ISSUE THREAD

**Issue by NotMehdy** [pishangujeniya/instagram-helper#64]
Hello. Thank you for your hard work on developing this. i have a Question, How can i delete all messages with no Skipped messages?
i mean i don't want to skip any message but it says the skipped messages number must be higher than 3. and when i write no number(after that coma) it automatically skip 10 last messages.
i'll be happy if you give me the code to unsend all the messages and Don't skip a single one

**Comment by pishangujeniya** [comment]
If you dont want to skip any recent messages, not even 3 then do write 4 into that,

And start unsending.

After everything completes, you can skip 4 messages manually with human hands, that is not a big task.

But, good news is I am working on this to allow 0 messaages also to be skipped, but that would take couple of weeks, because its tough to maintain something for free so I work in my leisure time only on this.
