### ISSUE TITLE
possible feature

### ISSUE THREAD

**Issue by chale96** [pishangujeniya/instagram-helper#8]
What about a for loop that collects all the chats id and goes through them all?

If you want to delete all the messages without doing it one by one.

**Comment by pishangujeniya** [comment]
There is a method which first collects all the messages ids in an array.

https://github.com/pishangujeniya/instagram-helper/blob/bba88162afca0303dd2c1d5f9505b674a4421193/InstagramHelper.js#L157

And 

There is a method which then starts deleting from the Array collected by the above method.

https://github.com/pishangujeniya/instagram-helper/blob/bba88162afca0303dd2c1d5f9505b674a4421193/InstagramHelper.js#L237

If you just want the ids of messages that you sent then those are stored in localstorage of browser by the first method

**Comment by pishangujeniya** [comment]
> 
> 
> There is a method which first collects all the messages ids in an array.
> 
> https://github.com/pishangujeniya/instagram-helper/blob/bba88162afca0303dd2c1d5f9505b674a4421193/InstagramHelper.js#L157
> 
> And
> 
> There is a method which then starts deleting from the Array collected by the above method.
> 
> https://github.com/pishangujeniya/instagram-helper/blob/bba88162afca0303dd2c1d5f9505b674a4421193/InstagramHelper.js#L237
> 
> If you just want the ids of messages that you sent then those are stored in the local storage of browser by the first method

I, later on, made a new method 
https://github.com/pishangujeniya/instagram-helper/blob/bba88162afca0303dd2c1d5f9505b674a4421193/InstagramHelper.js#L313
which will start deleting in chunks after getting messages id in chunks, because every time when we wanted to delete we need to first get all the messages id since the chat started and which was mostly time-consuming & repetitive process.

**Comment by chale96** [comment]
Although the  ```async getAllMessageIds(threadId)``` takes a `threadId` that is the specific chat. 

## The Idea:
The idea of the feature is that it will un-send the messages from all the chats

## How:
There should be a method to collect all the `threadId`s of all the chats and with a loop, start un-sending all the messages from them.

## Why:
Currently, the script needs to run for all chats and needs to update the `threadId`:
```JS
var ig  = new InstagramHelper();
ig.startUnsending("your_chat_thread_Id");
```

**Comment by pishangujeniya** [comment]
@chale96 , Ohh, I got it.

That is a good feature, but it needs bit research from where do Instagram gets all the chat thread ids.
It's a good feature request, but the purpose of this script and the scope remains low, because Instagram provides Too Many Requests Response 429 Code, and mostly the task is to re-run the script in the background every day for long chats.

I guess this repository will have that feature [https://github.com/ramtinak/InstagramApiSharp](https://github.com/ramtinak/InstagramApiSharp). You can check that.
